@ToDoAPI_HostAddress = http://localhost:32783

POST {{ToDoAPI_HostAddress}}/todoitems

###

POST {{ToDoAPI_HostAddress}}/todoitems
Content-Type: application/json

{
  "name":"walk dog",
  "isComplete":true
}
###

GET {{ToDoAPI_HostAddress}}/todoitems

###

GET {{ToDoAPI_HostAddress}}/todoitems/1

###

PUT {{ToDoAPI_HostAddress}}/todoitems/2
Content-Type: application/json

{
  "id": 2 ,
  "name": "feed fish",
  "isComplete": false
}

###

DELETE {{ToDoAPI_HostAddress}}/todoitems/2

###

GET {{ToDoAPI_HostAddress}}/todoitems/

###

GET {{ToDoAPI_HostAddress}}/todoitems/

###

GET {{ToDoAPI_HostAddress}}/todoitems/

###

GET {{ToDoAPI_HostAddress}}/todoitems/3

###
